### ISSUE TITLE
Making it work for Mac

### ISSUE THREAD

**Issue by holgersindbaek** [GuntisTreulands/JigsawDemo#1]
Hi Guntis

I'm about to create a jigsaw game for Mac and I've been looking into your code. I'm very new to playing around with Bezierpaths though and I'm not sure how to translate the UIBezierpaths into NSBezierpaths.

Would you be able to make a sample app for Mac (the moving and rotating isn't a priority)?

**Comment by GuntisTreulands** [comment]
Hi!, thanks for the interest.

Unfortunately I don't have time to create a full blown mac version of this demo, but I can adjust the code, so that it would "theoretically" work on OSX.  (Bezierpaths part) . Can You contact me @  gtreulands@gmail.com ?  I will send You back adjusted code.
